Add project status tracking and ability to change project status
illiakroshka/edu_db_labs pull request #60
Opened 2023-10-06 19:08 UTC by stasyukhymenko

2023-10-06 23:34 UTC, 1Laggy1 requested changes
Змінюй, що вважаєш за потрібним

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +**6.** Розробники мають можливість оновлювати статус своїх завдань.
Це ж не дія

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +**6.** Розробники мають можливість оновлювати статус своїх завдань.
І друге слово не дієслово

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +**4.** Користувач може переглядати деталі кожного завдання, включаючи статус, відповідального розробника, та опис завдання.
Тут теж друге слово не дієслово, і взагалі не дія

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +**7.** Система автоматично оновлює загальний статус розробки проекту на основі змін у статусах завдань.
Друге слово - дієслово

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +**8.** Замовник може перевірити актуальний статус розробки проекту в будь-який момент.
Не дія, друге слово повинно бути дієсловом

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +**_ПЕРЕДУМОВИ:_** Проект існує в системі, користувачі мають права на зміну статусу проекта.
Тут мабуть треба не користувачі, а Замовник. І в загальному повинно бути: Замовник є власником проекту.

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +- ChangeProjectStatus_EX_Unauthorized - Користувач не має прав на зміну статусу проекта.
Мабуть змінити на "Замовник не є власником проекту"?
Бо не зрозуміло чи тут інші користувачі, наприклад тімлід але він тут не до чого. І якщо Замовник є власником проекту, він в любому випадку буде мати доступ до зміну статусу

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +- ChangeProjectStatus_EX_PermissionDenied - Користувач намагається змінити статус проекта, на який він не має прав доступу.
А ось тут вже якраз те що Замовник є власником, як я зрозумів. В нас не може бути інших користувачів якщо взаємодіє саме Замовник з Системою

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +**_ОСНОВНИЙ СЦЕНАРІЙ:_**
Чомусь немає в сценарію в дужках помилок де вони можуть бути

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +
Результатом повинний бути іменник, не знаю як тут це зробити

2023-10-06 23:34 UTC, 1Laggy1 commented on docs/requirements/stakeholders-needs.md
> +**7.** Система автоматично оновлює загальний статус розробки проекту на основі змін у статусах завдань.
Можливо можна і так залишити

2023-10-07 18:12 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +**6.** Розробники мають можливість оновлювати статус своїх завдань.
5. Система відображає оновлення статусу завдань (наприклад, позначення завдання як виконане).

Прибрав взагалі розробника

2023-10-07 18:13 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +**4.** Користувач може переглядати деталі кожного завдання, включаючи статус, відповідального розробника, та опис завдання.
3 наче норм

4. Користувач переглядає деталі, опис та статус завдання, відповідального розробника.

2023-10-07 18:22 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +**7.** Система автоматично оновлює загальний статус розробки проекту на основі змін у статусах завдань.
6. Система оновлює автоматично загальний статус розробки проекту на основі змін у статусах завдань.

2023-10-07 18:23 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +**8.** Замовник може перевірити актуальний статус розробки проекту в будь-який момент.
7. Замовник перевіряє актуальний статус розробки за потреби.

2023-10-07 18:26 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +**_ПЕРЕДУМОВИ:_** Проект існує в системі, користувачі мають права на зміну статусу проекта.
**_ПЕРЕДУМОВИ:_** Проект існує в системі, замовник має доступ до інформації про статус розробки.

**_РЕЗУЛЬТАТ:_** Замовник може відстежувати поточний статус розробки проекту.

2023-10-07 18:27 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +**_ПЕРЕДУМОВИ:_** Проект існує в системі, користувачі мають права на зміну статусу проекта.
**_ПЕРЕДУМОВИ:_** Проект існує в системі, замовник є власником проекту.

2023-10-07 18:28 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +- ChangeProjectStatus_EX_Unauthorized - Користувач не має прав на зміну статусу проекта.
- ChangeProjectStatus_EX_Unauthorized - Замовник не є власником проекту.

2023-10-07 18:37 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +
**_РЕЗУЛЬТАТ:_** Замовник відстежує поточний статус розробки проекту.

2023-10-07 18:44 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +- ChangeProjectStatus_EX_PermissionDenied - Користувач намагається змінити статус проекта, на який він не має прав доступу.
Прибрав рядок 248

2023-10-07 18:48 UTC, stasyukhymenko commented on docs/requirements/stakeholders-needs.md
> +**_ОСНОВНИЙ СЦЕНАРІЙ:_**
**2.** Замовник обирає проект, для якого потрібно відстежувати статус розробки. (TrackDevelopmentStatus_EX_ProjectNotFound) (TrackDevelopmentStatus_EX_InternalError)

**3.** Система відображає інформацію про поточний статус розробки проекту, включаючи завдання, які вже виконані і ті, що ще в розробці. (TrackDevelopmentStatus_EX_PermissionDenied)

2023-10-07 21:38 UTC, 1Laggy1 approved these changes

2023-10-07 21:38 UTC, merged